spring:
  config:
    activate:
      on-profile: local
  ssl:
    bundle:
      jks:
        redis:
          key:
            alias: 1
            password: changeit
          keystore:
            location: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/redis/certificates/redis.p12
            password: changeit
            type: pkcs12
          truststore:
            location: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/redis/certificates/trust.p12
            password: changeit
            type: pkcs12
  data:
    redis:
      host: local.dev.swedenconnect.se
      port: 6379
      password: supersecret
      ssl:
        enabled: true
        bundle: redis
      ssl-ext:
        enable-hostname-verification: true
  session:
    timeout: 15m

server:
  error:
    whitelabel:
      enabled: true
    path: /#error
  reactive:
    session:
      timeout: 15m

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, loggers, auditevents
  server:
    port: 8444

logging:
  level:
    se:
      swedenconnect:
        spring:
          saml: DEBUG
        bankid: DEBUG

bankid:
  start-retry-duration: "PT2M"
  built-in-frontend: true
  server-root-certificate: classpath:bankid-trust-test.crt
  service-url: https://appapi2.test.bankid.com/rp/v6.0
  ui:
    provider:
      svg-logotype: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/icon/icon.svg
      svg-favicon: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/icon/favicon.svg
      png-favicon: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/icon/favicon.png
      name:
        sv: "Sweden Connect"
        en: "Sweden Connect"
    show-sp-message: true
    user-error:
      contact-email: contact@email.com
      show-contact-information: true
      show-trace-id: true
    user-message-defaults:
      fallback-sign-text:
        text: "Jag skriver härmed under den information som visades på föregående sida."
        format: plain_text
      login-text:
        text: "*Tänk på!* Logga aldrig in med ditt BankID då någon ringer och ber dig logga in."
        format: simple-markdown-v1
    override:
      directory-path: ${BANKID_INSTALL_DIR}/bankid-idp/env/local/overrides
    qr-code:
      display-qr-help: true

  relying-parties:
    - id: test-my-eid
      entity-ids:
        - http://sandbox.swedenconnect.se/testmyeid
        - http://sandbox.swedenconnect.se/testmyeid-sign
      credential:
        name: "test-cred"
        resource: file:${BANKID_INSTALL_DIR}/bankid-idp/env/swedenconnect/sandbox/certificate/FPTestcert4_20220818.p12
        alias: "1"
        password: "qwerty123"
        type: "PKCS12"
      user-message:
        inherit-default-login-text: false
        login-text:
          text: "Jag loggar härmed in till tjänsten Testa ditt eID.\n\n*Tänk på!* Logga aldrig in med ditt BankID då någon ringer och ber dig logga in."
          format: simple-markdown-v1
      bankid-requirements:
        pin-code-auth: false
        pin-code-sign: true

saml: 
  idp:
    entity-id: https://bankid.swedenconnect.se/idp/local
    base-url: https://local.dev.swedenconnect.se:${server.port}${server.servlet.context-path}
    metadata-providers:
      - location: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/metadata/local-metadata.xml
    credentials:
      sign:
        resource: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/idp-credentials/idp-credentials.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/idp-credentials/idp-credentials.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/idp-credentials/idp-credentials.jks
        alias: metadata
        password: secret
        type: JKS
    metadata:
      ui-info:
        display-names:
          en: BankID
          sv: BankID
        descriptions:
          en: BankID Identity Provider (Local)
          sv: BankID legitimeringstjänst (Local)
        logotypes:
          - path: /images/BankID_logo.svg
            height: 171
            width: 20
      organization:
        names:
          en: "Sweden Connect"
          sv: "Sweden Connect"
        display-names:
          en: "Sweden Connect"
          sv: "Sweden Connect"
        urls:
          en: https://www.swedenconnect.se/en
          sv: https://www.swedenconnect.se
      contact-persons:
        technical:
          company: "Sweden Connect"
          email-addresses:
            - operations@swedenconnect.se
        support:
          company: "Sweden Connect"
          email-addresses:
            - operations@swedenconnect.se
    session:
      module: "redis"
    replay:
      expiration: 10m 
    audit:
      file:
        log-file: ${BANKID_INSTALL_DIR}/bankid-idp/target/audit.log
      redis:
        type: "timeseries"
        name: "audit:ts"
      in-memory:
        capacity: 1000
---
spring:
  config:
    activate:
      on-profile: cluster
  ssl:
    bundle:
      jks:
        redis-cluster:
          key:
            alias: 1
            password: changeit
          keystore:
            location: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/redis-cluster/certificates/redis.p12
            password: changeit
            type: pkcs12
          truststore:
            location: file:${BANKID_INSTALL_DIR}/bankid-idp/env/local/redis-cluster/certificates/trust.p12
            password: changeit
            type: pkcs12      
  data:
    redis:
      password: supersecret
      cluster:
        nodes:
          - redis1.local.dev.swedenconnect.se:2001
          - redis2.local.dev.swedenconnect.se:2002
          - redis3.local.dev.swedenconnect.se:2003      
      cluster-ext:
        nat-translation:
          - from: "172.20.0.31:2001"
            to: "redis1.local.dev.swedenconnect.se:2001"
          - from: "172.20.0.32:2002"
            to: "redis2.local.dev.swedenconnect.se:2002"
          - from: "172.20.0.33:2003"
            to: "redis3.local.dev.swedenconnect.se:2003"      
      ssl:
        enabled: true
        bundle: "redis-cluster"
      ssl-ext:
        enable-hostname-verification: true        

