name: bankid-idp-local
networks:
  idp:
    name: idp

services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - idp
    volumes:
      - ./certificates:/tls
    environment:
      - REDIS_ARGS=--requirepass supersecret --tls-port 6379 --port 0 --tls-cert-file /tls/server.crt --tls-key-file /tls/server.key --tls-ca-cert-file /tls/ca.crt