name: Automated review steps
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - run: |
          sudo echo "127.0.0.1 local.dev.swedenconnect.se" | sudo tee -a /etc/hosts
          mvn clean verify --no-transfer-progress
